### ISSUE TITLE
Query finalizer called too early / segfault when reading results 

### ISSUE THREAD

**Issue by bf-tomnomnom** [smacker/go-tree-sitter#75]
The finalizer for `*Query` seems to be called too early, sometimes causing a segfault when - for example - calling `*QueryCursor.NextMatch`.

Here's some code that reproduces the segfault:

```go
package main

import (
	"bytes"

	sitter "github.com/smacker/go-tree-sitter"
	"github.com/smacker/go-tree-sitter/javascript"
)

func main() {

	source := bytes.Repeat([]byte("document.location = 'https://example.com';"), 10000)

	parser := sitter.NewParser()
	parser.SetLanguage(javascript.GetLanguage())

	tree := parser.Parse(nil, source)
	root := tree.RootNode()

	for i := 0; i < 100; i++ {
		query, _ := sitter.NewQuery(
			[]byte("(assignment_expression) @match"),
			javascript.GetLanguage(),
		)

		qc := sitter.NewQueryCursor()

		qc.Exec(query, root)

		for {
			// This call to qc.NextMatch() will sometimes cause a segfault
			match, exists := qc.NextMatch()
			if !exists || match == nil {
				break
			}
		}
	}
}
```

And the output: 

```
tom@work:~/src/github.com/bf-tomnomnom/tree-sitter-crash▶ go build && ./tree-sitter-crash
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8c0 pc=0x10464af08]

runtime stack:
runtime.throw({0x104662c9b?, 0x0?})
	/usr/local/go/src/runtime/panic.go:992 +0x50
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:802 +0x1e8

goroutine 1 [syscall]:
runtime.cgocall(0x10463b62c, 0x14000056d38)
	/usr/local/go/src/runtime/cgocall.go:157 +0x54 fp=0x14000056d00 sp=0x14000056cc0 pc=0x1045b08e4
github.com/smacker/go-tree-sitter._Cfunc_ts_query_cursor_next_match(0x600001c48090, 0x14001849a10)
	_cgo_gotypes.go:1021 +0x3c fp=0x14000056d30 sp=0x14000056d00 pc=0x104637c3c
github.com/smacker/go-tree-sitter.(*QueryCursor).NextMatch.func1(0x10468eca0?, 0x0?)
	/Users/tomhudson/pkg/mod/github.com/smacker/go-tree-sitter@v0.0.0-20220623130553-1191a8204295/bindings.go:886 +0x90 fp=0x14000056d80 sp=0x14000056d30 pc=0x104639c60
github.com/smacker/go-tree-sitter.(*QueryCursor).NextMatch(0x1400000e078)
	/Users/tomhudson/pkg/mod/github.com/smacker/go-tree-sitter@v0.0.0-20220623130553-1191a8204295/bindings.go:886 +0x4c fp=0x14000056ea0 sp=0x14000056d80 pc=0x10463988c
main.main()
	/Users/tomhudson/src/github.com/bf-tomnomnom/tree-sitter-crash/main.go:32 +0x214 fp=0x14000056f70 sp=0x14000056ea0 pc=0x10463a6e4
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x250 fp=0x14000056fd0 sp=0x14000056f70 pc=0x1045df020
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1259 +0x4 fp=0x14000056fd0 sp=0x14000056fd0 pc=0x1046090c4
```

I was able to figure out that if the setting of `*Query`'s finalizer [here](https://github.com/smacker/go-tree-sitter/blob/1191a8204295ea48d1d5fb2e6fd51474b13f94de/bindings.go#L740) is commented out and the code is re-built, then it runs to completion without crashing.

I don't have a great deal of experience with Cgo so it's a little beyond me to figure out exactly why this is happening and how to prevent it, sorry!

**Comment by smacker** [comment]
hi @bf-tomnomnom ! Thank you for the bug report. It should be fixed now.

**Comment by bf-tomnomnom** [comment]
@smacker that is superb; thank you for the fix and the speedy response! :)
